// <auto-generated />
namespace ETicaretWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class productorder2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(productorder2));
        
        string IMigrationMetadata.Id
        {
            get { return "202312231746465_product-order2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
