// <auto-generated />
namespace ETicaretWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatecreatedby : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatecreatedby));
        
        string IMigrationMetadata.Id
        {
            get { return "202312231646076_update-createdby"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
